### ISSUE TITLE
Tooltip displays giant rectangle

### ISSUE THREAD

**Issue by marcelomanzo** [ColinDuquesnoy/QDarkStyleSheet#174] opened 2019-05-25 12:58 UTC
### Describe Your Environment
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Windows
    - Release....................... 10
    - Platform...................... Windows-10-10.0.17763-SP0
    - Version....................... 10.0.17763
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.7.0
    - C Compiler.................... MSC v.1914 64 bit (AMD64)
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.7.0
* QT BINDINGS--------------------------------------------------------------------
    - PySide2 Version............... 5.12.3
    - PySide2 Qt Version............ 5.12.3
* QT ABSTRACTIONS----------------------------------------------------------------
    - qtpy Version.................. 1.7.1
    - qtpy Binding.................. pyqt5
    - qtpy Binding Variable......... os.environ['QT_API']
    - qtpy Import Name.............. qtpy
    - qtpy Status................... OK
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... 0.6.10
    - QDarkStyle.................... 2.6.8
### Language

Python

### Description / Steps to Reproduce [if necessary]

        self.powerWindStatusButon = QtWidgets.QPushButton(self.intelliboxVerticalLayoutWidget)
        self.powerWindStatusButon.setObjectName("powerWindStatusButon")
        self.powerWindStatusButon.setToolTip('Shortcut: ')

### Actual Result

![image](https://user-images.githubusercontent.com/12878783/58369618-e3b08200-7eca-11e9-8a3d-a7dd2542176d.png)

### Expected Results / Proposed Result

Small rectangle around text

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```
# code here to reproduce the problem
```

**Comment by dpizetta** [comment] 2019-05-25 13:24
Hi @marcelomanzo, wou that is weird. If I remember you are using the version from the github? If so, you can tell me which commit started/or which commit hash you are using right now? Thanks!

**Comment by marcelomanzo** [comment] 2019-05-25 13:52
I installed the version from pythonhosted andsame issue:
(srsvenv) C:\temp\srsvenv\Scripts>pip install qdarkstyle
Collecting qdarkstyle
  Using cached https://files.pythonhosted.org/packages/2b/ab/8996b69475feda604e8b2f60b7d3e48938c0e07f48532ee112ce097cc6de/QDarkStyle-2.6.8-py2.py3-none-any.whl
Installing collected packages: qdarkstyle
Successfully installed qdarkstyle-2.6.8
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(srsvenv) C:\temp\srsvenv\Scripts>

**Comment by dpizetta** [comment] 2019-06-01 03:20
@marcelomanzo  can you test using the example provided in qdarkstyle if you can reproduce this? The push button has a tooltip. I can't reproduce here with my machine. Tks

**Comment by dpizetta** [comment] 2019-06-02 01:12
Changing the milestone to try to reproduce the problem.

**Comment by marcelomanzo** [comment] 2019-06-02 01:52
issue still there, I will try to get a sample code for you

**Comment by teemu-l** [comment] 2019-06-05 10:55
I have the same problem here: https://github.com/teemu-l/execution-trace-viewer

Win10, Python 3.7, PyQt5 5.12.2, QDarkStyle 2.7

**Comment by LewisCarney** [comment] 2019-06-07 08:30
For some reason the opacity value seems to be causing the issue. I made this workaround which might help for now:

x = qdarkstyle.load_stylesheet_pyside2()
x = x.replace(
            "QToolTip {\n    background-color: #148CD2;\n    border: 1px solid #19232D;\n    color: #19232D;\n    padding: 0;   /*remove padding, for fix combo box tooltip*/\n    opacity: 230; /*reducing transparency to read better*/\n}",
            "QToolTip {\n    background-color: #148CD2;\n    border: 1px solid #19232D;\n    color: #19232D;\n    padding: 0;   /*remove padding, for fix combo box tooltip*/\n}"
        )

self.setStyleSheet(x)

**Comment by PaTiToMaSteR** [comment] 2019-06-15 14:13
@LewisCarney that's the solution, but in the current source code doesn't fit that long text, my change was:
```
fixedStyle = qdarkstyle.load_stylesheet_pyside2()
fixedStyle = fixedStyle.replace(
"opacity: 230;",
""
)
```
Hope it help someone!
Thank you all!

**Comment by dpizetta** [comment] 2019-06-18 03:31
Can you try to substitute this:

"QToolTip {\n background-color: #148CD2;\n border: 1px solid #19232D;\n color: #19232D;\n padding: 0; /remove padding, for fix combo box tooltip/\n opacity: 230; /reducing transparency to read better/\n}"

**For this (hex with opacity):**

"QToolTip {\n background-color: #148CD2E6;\n border: 1px solid #19232D;\n color: #19232D;\n padding: 0; /remove padding, for fix combo box tooltip/\n}")

**And/or this one (rgba):**

"QToolTip {\n background-color: rgba(20, 140, 210, 1);\n border: 1px solid #19232D;\n color: #19232D;\n padding: 0; /remove padding, for fix combo box tooltip/\n}")

Tks

**Comment by dpizetta** [comment] 2020-01-09 17:46
As the solution proposed is working at this moment, closing this issue. Tks to everyone.

**Closed by dpizetta** 2020-01-09 17:46 UTC
Labels: bug, investigate, unstyled widget
