### ISSUE TITLE
QComboBox expands the last chosen item

### ISSUE THREAD

**Issue by jkulskis** [ColinDuquesnoy/QDarkStyleSheet#200] opened 2019-07-12 02:52 UTC
### Describe Your Environment

Please, report the output of the command (from v2.6+):

`$ qdarkstyle --all`
```
* OPERATING SYSTEM---------------------------------------------------------------
    - System........................ Linux
    - Release....................... 4.15.0-20-generic
    - Platform...................... Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19.1-tessa
    - Version....................... #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
* PYTHON DISTRIBUTION------------------------------------------------------------
    - Version....................... 3.6.8
    - C Compiler.................... GCC 8.0.1 20180414 (experimental) [trunk revision 259383
    - C API Version................. 1013
    - Implementation................ cpython
    - Implementation Version........ 3.6.8
* QT BINDINGS--------------------------------------------------------------------
    - PySide2 Version............... 5.13.0
    - PySide2 Qt Version............ 5.13.0
* QT ABSTRACTIONS----------------------------------------------------------------
    - Status........................ No Qt abstractions available!
* PYTHON PACKAGES----------------------------------------------------------------
    - helpdev....................... (0.6.10)
    - QDarkStyle.................... (2.7)
```

[Versions from your environment]

- QDarkStyle: 2.7
- OS: Linux Mint 19.1 Tessa
- Python: 3.6.8
- PySide2: 5.13

### Language

Python

### Description / Steps to Reproduce [if necessary]

Relevant UI setup code I used to add the combo box (generated by pyuic5) with a Dialog creation to provide a reproducible example:

```python
from PySide2 import QtCore, QtGui, QtWidgets
import qdarkstyle
import sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(875, 527)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox.setItemText(0, _translate("Dialog", "1 day"))
        self.comboBox.setItemText(1, _translate("Dialog", "1 week"))
        self.comboBox.setItemText(2, _translate("Dialog", "3 months"))
        self.comboBox.setItemText(3, _translate("Dialog", "6 months"))
        self.comboBox.setItemText(4, _translate("Dialog", "1 year"))
        self.comboBox.setItemText(5, _translate("Dialog", "3 years"))
        self.comboBox.setItemText(6, _translate("Dialog", "5 years"))
        self.comboBox.setItemText(7, _translate("Dialog", "max"))

class Dialog(QtWidgets.QDialog):
    def __init__(self):
        super(Dialog, self).__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = Dialog()
    window.show()
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyside2())
    sys.exit(app.exec_())
```

When I open up the combobox, the item that was last chosen will increase in size as shown in the image below:
![blown up item in combobox](https://i.imgur.com/vJYsm8b.png)

I tried to revert back to the default qt theme, and everything worked fine. I suspect it has something to do with Linux Mint or other aspects of my environment since I asked a question on StackOverflow, and a user commented that the code worked fine for them on linux.

**Comment by goanpeca** [comment] 2019-07-12 04:11
@jkulskis could you try doing something like setting a styled delegate for the combo box?

```python
from PySide2 import QtCore, QtGui, QtWidgets
...
    delegate = QStyledItemDelegate()
    self.comboBox = QtWidgets.QComboBox(Dialog)
    self.comboBox.setItemDelegate(delegate)
```

**Comment by jkulskis** [comment] 2019-07-12 04:37
@goanpeca This fixed the extra expansion, but now the combobox opens much higher than the dialog window instead of as a dropdown.

**Unopened:**
![Unopened Combobox](https://i.imgur.com/30sKMZI.png)

**Opened**
![Opened Combobox](https://i.imgur.com/tv8CohR.png)

**Comment by goanpeca** [comment] 2019-07-12 04:53
Ok! We will see how we can fix that. Thanks for testing.

**Comment by jkulskis** [comment] 2019-07-12 04:56
Thank you for the quick help!

**Comment by cculianu** [comment] 2019-08-17 10:38
Note this also happens on macOS -- same thing. Screenshot attached.

It doesn't happen with PyQt5 5.12.x, but happens only starting with PyQt5 5.13.x.

So the issue is not PySide-specific nor PyQt5 specific -- but rather depends on the underlying Qt version.  (Works on 5.12, broken on 5.13).

# Screenshot

![photo_2019-08-17 13 37 46](https://user-images.githubusercontent.com/266627/63210209-37122500-c0f4-11e9-9d8c-c692cb57cc00.jpeg)

**Comment by asch99** [comment] 2019-10-04 17:09
This issue can be fixed by adding one line in style.qss and recompiling:
add the line 
```
  height: 12px;
```

to QComboBox::item:checked

so it reads
```
QComboBox::item:checked {
  font-weight: bold;
  height: 12px;
}
```
Do you want a PR for this? And if so, a PR with just this modified file, or do you want all recompiled rc files too?

**Comment by cculianu** [comment] 2019-10-04 19:14
On Mojave with PyQt5 5.13.1 this still happens -- but with this fix it does not. Note that 14px for me looks better. But 12px is pretty good too.

Consider adding this or something similar ...

**Comment by tanimislam** [comment] 2019-11-07 05:56
I also see thiis issue with the ``PyQt5`` style sheet.

**Comment by dpizetta** [comment] 2019-11-19 14:19
@goanpeca could you take a look at that? Tks

**Comment by goanpeca** [comment] 2019-11-19 14:30
Will do!

QComboBoxes are a headache to style right :-| !

**Comment by dpizetta** [comment] 2019-11-19 14:32
I see :( Thank you!

**Comment by mikeleppane** [comment] 2019-11-26 20:56
I was also having this same problem with QComboBox. First I tried adding that height property like @asch99 recommended. I could not get it to work. Then I tried that original solution what  @goanpeca suggested which is setting that styled delegate to ComboBox. That solution worked perfectly for me! 

My environment is as follows:
- QDarkStyle: 2.7
- OS: Linux Ubuntu 18.04.3 LTS
- Python: 3.6.8
- PyQt5: 5.13.0
- Qt: 5.13.0

**Comment by asch99** [comment] 2019-11-26 21:37
Yeah, I agree that my proposed solution does not seems to be the one-fix-for-all solution. What works reliably (so far) for me is to either modify the stylesheet of the combobox itself, or of the parent container. 

E.g. having an QApplication with a QTabWidget, containing (as a tab) a QWidget, containing a QComboBox then modifying the stylesheet of the QWidget or the QCombobox fixes the problem. However, modifying the stylesheet of the QApplication does not fix the problem.

The applied modification is:
            WIDGET_NAME.setStyleSheet(
                """
                QComboBox::item:checked {
                  height: 12px;
                  border: 1px solid #32414B;
                  margin-top: 0px;
                  margin-bottom: 0px;
                  padding: 4px;
                  padding-left: 0px;
                }
                """
            )
where you have to use the actual widget name of your own widget.

**Comment by dpizetta** [comment] 2020-01-13 18:48
@goanpeca  some news about this one? Sorry for my lack of communication, now I want to run with these changes as I some time. Thanks

**Comment by goanpeca** [comment] 2020-01-13 21:14
Not much :-|

**Comment by dpizetta** [comment] 2020-01-20 01:57
I changed this to next version, so we can release the 2.8 :)

**Comment by Daguerreo** [comment] 2020-03-10 10:30
> Yeah, I agree that my proposed solution does not seems to be the one-fix-for-all solution. What works reliably (so far) for me is to either modify the stylesheet of the combobox itself, or of the parent container.
> 
> E.g. having an QApplication with a QTabWidget, containing (as a tab) a QWidget, containing a QComboBox then modifying the stylesheet of the QWidget or the QCombobox fixes the problem. However, modifying the stylesheet of the QApplication does not fix the problem.
> 
> The applied modification is:
> WIDGET_NAME.setStyleSheet(
> """
> QComboBox::item:checked {
> height: 12px;
> border: 1px solid #32414B;
> margin-top: 0px;
> margin-bottom: 0px;
> padding: 4px;
> padding-left: 0px;
> }
> """
> )
> where you have to use the actual widget name of your own widget.
> 
> The delegate solution also works, but then you loose part of the qdarkstyle formatting.

This worked for me on Linux Slackware 14.2, QDarkStyle 2.8 and Qt 5.14.1

**Comment by tanimislam** [comment] 2020-05-20 02:01
[qmodern](https://github.com/gmarull/qtmodern) does not have the failing QComboBox with PyQt5. Its own dark mode looks as good as this module. Perhaps we should use that instead?

**Comment by dpizetta** [comment] 2021-03-13 03:06
@jkulskis @tanimislam @mikeleppane Could you please check if the [current solution](2dd3a9f2ebe52333987b476571c040d11bb67073) in development works for everybody?

**Comment by SomberNight** [comment] 2021-03-13 12:07
@dpizetta I have tested on a config where I could previously reproduce and can confirm the develop branch fixed this issue.
However there is now another issue, which might be related; for that I opened https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/263

**Closed** 2021-03-29 03:47 UTC
Labels: bug

**Comment by vrot2000** [comment] 2023-11-23 21:19
Same thing in Ubuntu under QT until 6.6.0 
Fix:
`
QComboBox::item:checked {
  /*font-weight: bold;*/
  height: 11px;
}`
