### ISSUE TITLE
Q_INIT_RESOURCE trouble

### ISSUE THREAD

**Issue by Jihadist** [ColinDuquesnoy/QDarkStyleSheet#283] opened 2021-05-31 13:31 UTC
[Versions from your environment]

- QDarkStyle: 3+
- OS: Windows 7
- NoPython: just C++/qmake

[If used, please inform their versions]

- QT_API: 5.15.2

### Language

C++

### Description / Steps to Reproduce [if necessary]

[How to Q_INIT_RESOURCE both styles (light and dark)?]

They have the same resources name so Qt macro doesnt work correctly and inits only first qrc file

### Actual Result

Inialization only one (UB ?)

### Expected Results / Proposed Result

Initialization both resource files

### Relevant Code [if necessary]

[A piece of code to reproduce and/or fix this issue]

```
RESOURCES += \
    styles/QDarkStyleSheet/qdarkstyle/light/style.qrc \
    styles/QDarkStyleSheet/qdarkstyle/dark/style.qrc \


Q_INIT_RESOURCE(style);
```

**Comment by dpizetta** [comment] 2021-11-29 12:52
@Jihadist thanks for reporting, I think this is a duplicate of #273. There you will find a possible solution for now to use both. By now we can't see another solution.

**Closed by dpizetta** 2021-11-29 12:52 UTC
Labels: duplicate
