### ISSUE TITLE
4K 

### ISSUE THREAD

**Issue by gjaegy** [ColinDuquesnoy/QDarkStyleSheet#49] opened 2017-03-02 11:32 UTC
Very nice work !!

However, when using a 4K display, it doesn't look as nice as it does in standard FullHD resolution.

**Comment by ColinDuquesnoy** [comment] 2017-03-07 18:04
> it doesn't look as nice as it does in standard FullHD resolution.

What parts does not looks good? I don't have a 4K screen and I have no clue what the problem is. 
What is your OS? What version of Qt are you using?

**Comment by Ybalrid** [comment] 2017-03-12 03:33
4K screens and other really high resolution screens are a pain to deal with GUI-wise, specially on windows. (On MacOS, if you have a "retina" screen the whole OS is built for that.)

Windows is doing a fairly poor job at scaling the desktop when using an "high DPI" screen. Qt has some information and guidelines about theses issues here http://doc.qt.io/qt-5/highdpi.html

Some UI start looking absolutely disgusting when Windows kicks in it's "DPI Scaling" crap. One example that comes to mind is the Steam client.

But if the problem is like "stuff looks a bit blurry" and you're under Windows, I'm afraid there isn't much that can be done about that. Maybe having higher resolution files in ;/qss_icons

But without more info about @gjaegy exact issue, it's hard to know 😐

**Comment by ColinDuquesnoy** [comment] 2017-04-09 07:50
@gjaegy ping

**Comment by gjaegy** [comment] 2017-04-10 12:50
Hi Colin,

really sorry for the delay. Below is a screenshot of the stylesheet shown on a 4k display.

what bothers me a bit apart the resolution of the icons, this is due to the source resolution of the images of course):
- tool icons spacing too large
- some alignment problems
- I don't really like the "dotted lines" look (but this is a subjective opinion)
- some double lines, for instance, on the property browser on the right, below the "scale" entry
- text of some buttons cut (bottom right, likely related to spacing issue mentioned above).

I hope that helps !

![edit](https://cloud.githubusercontent.com/assets/900305/24862320/785bfde4-1dfc-11e7-9cc0-4f7b458af5a0.jpg)

**Comment by ColinDuquesnoy** [comment] 2017-04-29 16:10
What Qt toolkit are you using? Qt4 or Qt5? I know Qt5 has better support for high resolution/high dpi screens. 

As I don't have a 4k screen, I won't fix this issue myself. Feel free to submit a PR if you find some tweaks that improve the quality of the stylesheet on 4k screens and don't break anything on standard screens.

**Closed by ColinDuquesnoy** 2017-04-29 16:10 UTC
