### ISSUE TITLE
Combobox style sheet is breaking

### ISSUE THREAD

**Issue by rishabh3354** [ColinDuquesnoy/QDarkStyleSheet#285] opened 2021-06-18 16:36 UTC
![IMG20210618220426](https://user-images.githubusercontent.com/26843758/122592048-7196d100-d081-11eb-8824-8c6eafbe8b5a.jpg)
![IMG20210618220426](https://user-images.githubusercontent.com/26843758/122592048-7196d100-d081-11eb-8824-8c6eafbe8b5a.jpg)

**Comment by rishabh3354** [comment] 2021-06-18 17:04
And also i figured it out , it is breaking because of this:

QComboBox::item:checked {
  font-weight: bold;
}

**Comment by MartinDelille** [comment] 2021-07-02 15:30
I also reproduce it with a simple code:

```cpp
// MainWindow.cpp

#include "MainWindow.h"
#include "ui_MainWindow.h"

MainWindow::MainWindow(QWidget *parent)
	: QMainWindow(parent)
	, ui(new Ui::MainWindow) {
	ui->setupUi(this);
	ui->comboBox->addItem("one");
	ui->comboBox->addItem("two");
	ui->comboBox->addItem("three");
}

MainWindow::~MainWindow() {
	delete ui;
}
```
```cpp
// main.cpp

#include "MainWindow.h"

#include <QApplication>
#include <QFile>

int main(int argc,
         char *argv[]) {
	QApplication a(argc, argv);
	// Set dark style sheet
	QFile styleFile(":qdarkstyle/dark/style.qss");

	if (styleFile.exists()) {
		styleFile.open(QFile::ReadOnly | QFile::Text);
		QTextStream ts(&styleFile);
		a.setStyleSheet(ts.readAll());
	}

	MainWindow w;
	w.show();

	return a.exec();
}
```
<img width="521" alt="Capture d’écran 2021-07-02 à 17 15 40" src="https://user-images.githubusercontent.com/879889/124296476-4967a180-db5a-11eb-8e1e-74872b0104c0.png">

**Comment by MartinDelille** [comment] 2021-07-02 15:34
I noticed also that this issue occurs in Qt 5.15 but not 5.12.

**Comment by rishabh3354** [comment] 2021-07-02 23:30
Please fix it in next update

**Comment by rishabh3354** [comment] 2021-07-04 22:04
Also another issue with qcombobox, when i set the icon on qcombobox, text and icon are overlaping.
Please fix that one also.
thanks!

**Comment by ntjess** [comment] 2021-11-17 04:30
Duplicate of #282?

**Closed** 2021-11-29 12:43 UTC
Labels: duplicate
