### ISSUE TITLE
Qt 5.15 MacOS - No reaction on Button-Click

### ISSUE THREAD

**Issue by wws61** [ColinDuquesnoy/QDarkStyleSheet#235] opened 2020-05-29 10:33 UTC
Using the stylesheet under Qt, pure C++/QtWidgets under MacOS and Windows. With the release of Qt 5.15 the Mac-Version don't work anymore as expected. 
There ist no reaction on Button-Clicks in MessageBoxes, Dialogs etc. Windows Version still works.
Thanks for any hint!

**Comment by AdrianDAlessandro** [comment] 2020-06-10 11:34
I have also came across this issue. I am using PySide2 with Python 3.7. The buttons work fine in the default style, but the stop responding to a click after I apply qdarkstyle. Minimal code to reproduce:

```python
import sys
import qdarkstyle
from PySide2.QtCore import Slot
from PySide2.QtWidgets import QApplication, QPushButton

@Slot()
def say_hello():
    print("Hello!")

app = QApplication(sys.argv)
button = QPushButton("Click Me!")
button.clicked.connect(say_hello)

# Comment out and the button works
app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api="pyside2"))

button.show()
app.exec_()
```

**Comment by AdrianDAlessandro** [comment] 2020-06-10 11:59
The button actually works in the above example if you resize the window! This example shows the problem. The difference is I'm displaying the button with QHBoxLayout in a QWidget

```python
import sys
import qdarkstyle
from PySide2.QtCore import Slot
from PySide2.QtWidgets import QApplication, QHBoxLayout, QPushButton, QWidget

@Slot()
def say_hello():
    print("Hello!")

app = QApplication(sys.argv)
widget = QWidget()
button = QPushButton("Click Me!")
button.clicked.connect(say_hello)
layout = QHBoxLayout()
layout.addWidget(button)
widget.setLayout(layout)

# Comment out and the button works
app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api="pyside2"))

widget.show()
app.exec_()
```

**Comment by wws61** [comment] 2020-06-12 08:38
It doesn't work, even in MessageBoxes, Dialogs etc. Still looking for a solution...

**Comment by dalonsoa** [comment] 2020-06-12 08:50
I can reproduce the error in 
- MacOS==10.15.5
- Python==3.8 
- PySide2==5.15.0
- QDarkStyle==2.8.1

**Comment by dpizetta** [comment] 2020-06-13 13:53
@wws61 @dalonsoa  @AdrianDAlessandro  thanks for pointing this out. It seems we will have some problems with the new release 5.15. 

@dalonsoa  Could you try with pyqt5?. It would be very nice to retrieve more info, and then running helpdev --all, so we can get all your configuration and dependencies. Tks

You can confirm that it works fine in previous versions?

**Comment by dpizetta** [comment] 2020-06-13 13:55
@goanpeca could you get this one, I remember you have a Mac :) I can test here on Windows and Linux Tks

**Comment by AdrianDAlessandro** [comment] 2020-06-15 12:21
@dpizetta I can reproduce the error in PyQt5==5.15.0

I can also confirm that the buttons _do_ work in:
- PySide2==5.14.2.2
- PyQt5==5.14.2

This is all with:
- MacOS==10.15.5
- Python==3.7.7
- QDarkStyle==2.8.1

**Comment by xmrdsc** [comment] 2020-07-24 00:08
- MacOS 10.15.4
- Qt 5.15.0 from Brew
- QtWidgets C++ application

Interestingly enough, there seems to be a small clickable area, I've highlighted it here:

![https://i.imgur.com/boprdPP.png](https://i.imgur.com/boprdPP.png)

Resizing doesn't fix it for me. The "clickable area" stays the same.

**Comment by cudmore** [comment] 2020-09-09 02:23
I confirm the same issure with PyQt5==5.15.0 on macOS 10.15.6

Problem is fixed by downgrading to PQt5==5.13.0
I am having similar issues with recent versions of PyQtGraph?

**Comment by dpizetta** [comment] 2020-09-10 12:17
Hi all, Qt 5.15 was recently released and I'm personally having problems with this distribution with other things. For the projects I work we have set to use only LTS versions, limiting to the most stable one, i.e 5.12, we have some other problems even with 5.13. For now, I would recommend the same until we get those issues fixed. In Qt forums, we saw many issues that appear with Qt 5.15, so it seems that now after the official release, they found more problems. We will be heads up.

**Comment by dannagle** [comment] 2020-11-24 21:42
Dark buttons seems to be working again with Qt 5.15.1. Using Big Sur on Intel.

**Comment by dpizetta** [comment] 2021-03-29 04:18
Hi guys, you can confirm if Qt 5.15+ can solve this? Tks

**Comment by dannagle** [comment] 2021-03-30 02:24
I installed your latest release v2.8.1. Styled buttons are working on Qt 5.15.2 Big Sur.

**Comment by dpizetta** [comment] 2021-03-30 04:16
@dannagle thanks.

A note for future references: Many issues can be solved when using the highest patch version available. We will be always testing on the last one for each major/minor version.

**Closed by dpizetta** 2021-03-30 04:16 UTC
Labels: investigate, qt-5.15
